# Generated by Django 5.2.5 on 2025-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('image', models.ImageField(upload_to='alerts/images/')),
                ('link_in_google_map', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
